image: docker:latest

services:
  - docker:dind

stages:
- build
- test
- integration
- deploy

build_img:
  stage: build
  script:
    - docker build -t cryptoIA:untested .

unit_test:
  stage: test
  script:
    - echo '' >> requirements.txt && echo 'coverage' >> requirements.txt
    - pip install --user -r requirements.txt && echo 'Env configured [x]'
    - /root/.local/bin/coverage run --source='.' manage.py test
    - /root/.local/bin/coverage report

quality_check:
  stage: test
  script:
    - python -m pip install flake8
    - python -c 'from Quality_check import quality_check; quality_check()'

integration_dev:
  stage: integration
  only: ['dev']
  script:
    - docker login -u matthieuBouamama -p ${CI_GITHUB_PACKAGE} docker.pkg.github.com
    - docker build -t docker.pkg.github.com/bouamamaMatthieu/cryptoIA/cryptoIA:latest .
    - docker push docker.pkg.github.com/bouamamaMatthieu/cryptoIA/cryptoIA:latest

integration_master:
  stage: integration
  only: ['master']
  script:
    - docker login -u matthieuBouamama -p ${CI_GITHUB_PACKAGE} docker.pkg.github.com
    - docker build -t docker.pkg.github.com/bouamamaMatthieu/cryptoIA/cryptoIA:1.6.0 .
    - docker push docker.pkg.github.com/bouamamaMatthieu/cryptoIA/cryptoIA:1.6.0

deploy_preprod:
  stage: deploy
  only: ['dev']
  script:
    - echo test

deploy_prod:
  stage: deploy
  only: ['master']
  script:
    - echo test